### ISSUE TITLE
SS-NAN model

### ISSUE THREAD

**Issue by Aashish792** [amjltc295/VITON_realtime#15]
I am not being able to Download pretrained SS-NAN model could you please upload this in a drive and share its link.
it would be very helpful for me as well a lot of people to see the demo of the program in their own machine

**Comment by amjltc295** [comment]
Unfortunately I'm not working on virtual try-on research and do not have the model anymore :(
Please note that this was just a demo project for makeNTU with lots of dirty code and should be deprecated.
You could ask the author of SS-NAN for the model or search for other latest models such as https://github.com/PeikeLi/Self-Correction-Human-Parsing

**Comment by Aashish792** [comment]
Hello Ya-Laing Chang,

Could you help me with this project i am trying very hard but any code
isn't working for me.

I have selected this as my final graduation project and i need to do it any
how.

Please any code just to see a demo may be a great help for me.

Thanks

**Comment by amjltc295** [comment]
As your graduation project I think you should write the code yourself...

**Comment by Aashish792** [comment]
I tried my best to code but there are a lot of error. i just want to see a
running project so that i could get a blueprint of project.

Thanks
