### ISSUE TITLE
Cannot download AttResnet101FCN_lip_0023.h5

### ISSUE THREAD

**Issue by binhmuc** [amjltc295/VITON_realtime#5]
I try to download AttResnet101FCN_lip_0023.h5 in this doc. However the site babu need registration. I try to create a account but required China number phone and i don't have. I'm not from China. So can  you upload AttResnet101FCN_lip_0023.h5 in other host, like google driver to allow anyone can download. Tks.

**Comment by anilkumar2444** [comment]
I am also unable to download the mentioned model. Can you please upload the mode. It will be very helpful. Thanks.

**Comment by amjltc295** [comment]
I'm not the author of the model and I cannot download it as well. 
I'm not sure it is okay to upload the old one. Please see https://github.com/llltttppp/SS-NAN and ask @llltttppp
If it fails to work, you could try to find another human parser. I believe there is a better one now.

**Comment by Eby-123** [comment]
I have downloaded.How about sending AttResnet101FCN_lip_0023.h5 to your email?

**Comment by jatinkatyal13** [comment]
@Eby-123 can you mail the model to me too ?
